const portalData = [
    {
      id: 1,
      title: "Breaking News: Global Tech Summit 2024",
      author: "John Doe",
      summary: "The Global Tech Summit 2024 has kicked off, featuring keynote speeches from industry leaders...",
      category: "Technology",
      date: "2024-09-15",
      views: 15000,
      comments: 50,
      image: "https://picsum.photos/800/400?random=1"
    },
    {
      id: 2,
      title: "How AI is Changing the Healthcare Industry",
      author: "Jane Smith",
      summary: "AI is revolutionizing healthcare with advanced diagnostics, personalized treatments...",
      category: "Health",
      date: "2024-09-14",
      views: 13500,
      comments: 45,
      image: "https://picsum.photos/800/400?random=2"
    },
    {
      id: 3,
      title: "10 Ways to Improve Your Productivity",
      author: "Mark Johnson",
      summary: "These simple productivity hacks will help you get more done in less time...",
      category: "Lifestyle",
      date: "2024-09-13",
      views: 12000,
      comments: 30,
      image: "https://picsum.photos/800/400?random=3"
    },
    {
      id: 4,
      title: "The Future of Electric Cars: What to Expect in 2025",
      author: "Emily White",
      summary: "Electric vehicles are becoming more affordable and efficient. Here's what's in store for 2025...",
      category: "Automotive",
      date: "2024-09-12",
      views: 9000,
      comments: 22,
      image: "https://picsum.photos/800/400?random=4"
    },
    {
      id: 5,
      title: "The Rise of Remote Work: Trends and Predictions",
      author: "David Brown",
      summary: "Remote work is here to stay. We explore the latest trends and predictions for the future...",
      category: "Business",
      date: "2024-09-11",
      views: 8500,
      comments: 18,
      image: "https://picsum.photos/800/400?random=5"
    },
    {
      id: 6,
      title: "Top 5 Gadgets to Look Out for in 2024",
      author: "Sara Wilson",
      summary: "2024 is shaping up to be an exciting year for tech enthusiasts. Here are the top 5 gadgets to watch...",
      category: "Technology",
      date: "2024-09-10",
      views: 16000,
      comments: 55,
      image: "https://picsum.photos/800/400?random=6"
    },
    {
      id: 7,
      title: "Healthy Eating on a Budget: Tips and Tricks",
      author: "Lisa Adams",
      summary: "Eating healthy doesn't have to be expensive. Discover tips to maintain a healthy diet on a budget...",
      category: "Health",
      date: "2024-09-09",
      views: 7800,
      comments: 20,
      image: "https://picsum.photos/800/400?random=7"
    },
    {
      id: 8,
      title: "The Best Travel Destinations for 2024",
      author: "Peter Collins",
      summary: "Planning a vacation in 2024? Check out these top travel destinations that offer breathtaking views...",
      category: "Travel",
      date: "2024-09-08",
      views: 11000,
      comments: 35,
      image: "https://picsum.photos/800/400?random=8"
    },
    {
      id: 9,
      title: "The Importance of Mental Health in the Workplace",
      author: "Chris Green",
      summary: "Mental health awareness is crucial for a productive and healthy work environment...",
      category: "Health",
      date: "2024-09-07",
      views: 9500,
      comments: 40,
      image: "https://picsum.photos/800/400?random=9"
    },
    {
      id: 10,
      title: "How to Start Your Own Online Business",
      author: "Anna Baker",
      summary: "Starting an online business can be daunting, but these steps will set you on the right path...",
      category: "Business",
      date: "2024-09-06",
      views: 14000,
      comments: 60,
      image: "https://picsum.photos/800/400?random=10"
    },
    {
      id: 11,
      title: "The Future of Renewable Energy in 2024",
      author: "Michael Green",
      summary: "Renewable energy sources are expected to lead the energy market by 2024. Discover the trends and innovations...",
      category: "Environment",
      date: "2024-09-05",
      views: 17500,
      comments: 48,
      image: "https://picsum.photos/800/400?random=11"
    },
    {
      id: 12,
      title: "Exploring the Deep Sea: New Discoveries",
      author: "Sandra Lee",
      summary: "Scientists have uncovered fascinating new species in the deep sea. Learn about the most recent findings...",
      category: "Science",
      date: "2024-09-04",
      views: 19000,
      comments: 52,
      image: "https://picsum.photos/800/400?random=12"
    },
    {
      id: 13,
      title: "The Evolution of Virtual Reality Gaming",
      author: "Alex Martin",
      summary: "Virtual reality gaming has transformed the gaming industry. Here's what the future holds...",
      category: "Gaming",
      date: "2024-09-03",
      views: 21000,
      comments: 75,
      image: "https://picsum.photos/800/400?random=13"
    },
    {
      id: 14,
      title: "Top 10 Best Books to Read in 2024",
      author: "Olivia Thompson",
      summary: "Looking for new books to add to your reading list? Here are the top picks for 2024...",
      category: "Lifestyle",
      date: "2024-09-02",
      views: 15500,
      comments: 34,
      image: "https://picsum.photos/800/400?random=14"
    },
    {
      id: 15,
      title: "How 5G is Revolutionizing Communication",
      author: "James Robinson",
      summary: "5G technology is setting new standards for speed and connectivity. Explore its impact on communication...",
      category: "Technology",
      date: "2024-09-01",
      views: 23000,
      comments: 85,
      image: "https://picsum.photos/800/400?random=15"
    },
    {
      id: 16,
      title: "The Art of Meditation: A Beginner’s Guide",
      author: "Emma Davis",
      summary: "Meditation is an ancient practice that can reduce stress and enhance mindfulness. Learn how to get started...",
      category: "Health",
      date: "2024-08-31",
      views: 9500,
      comments: 20,
      image: "https://picsum.photos/800/400?random=16"
    },
    {
      id: 17,
      title: "Discovering the Hidden Gems of Europe",
      author: "Sophia Wright",
      summary: "Europe is full of hidden treasures waiting to be discovered. Check out these underrated travel destinations...",
      category: "Travel",
      date: "2024-08-30",
      views: 12500,
      comments: 28,
      image: "https://picsum.photos/800/400?random=17"
    },
    {
      id: 18,
      title: "Climate Change and Its Impact on Wildlife",
      author: "Benjamin Scott",
      summary: "Climate change is drastically affecting wildlife across the globe. Learn how species are adapting to the changes...",
      category: "Environment",
      date: "2024-08-29",
      views: 14000,
      comments: 38,
      image: "https://picsum.photos/800/400?random=18"
    },
    {
      id: 19,
      title: "The Rise of Electric Bikes: A Greener Alternative",
      author: "Daniel Harris",
      summary: "Electric bikes are gaining popularity as a sustainable mode of transport. Here's everything you need to know...",
      category: "Automotive",
      date: "2024-08-28",
      views: 10500,
      comments: 15,
      image: "https://picsum.photos/800/400?random=19"
    },
    {
      id: 20,
      title: "Mastering the Art of Photography",
      author: "Isabella Clark",
      summary: "Whether you're a beginner or a pro, mastering photography takes time and skill. Discover top tips from experts...",
      category: "Lifestyle",
      date: "2024-08-27",
      views: 13500,
      comments: 25,
      image: "https://picsum.photos/800/400?random=20"
    },
    {
      id: 21,
      title: "The Future of Artificial Intelligence",
      author: "John Doe",
      summary: "Artificial intelligence is rapidly advancing. What does the future hold for AI in various industries?",
      category: "Technology",
      date: "2024-08-26",
      views: 20000,
      comments: 100,
      image: "https://picsum.photos/800/400?random=21"
    },
    {
      id: 22,
      title: "How to Achieve Financial Freedom by 30",
      author: "Jane Smith",
      summary: "Financial independence is a goal for many. Here are some tips to achieve it before you turn 30...",
      category: "Finance",
      date: "2024-08-25",
      views: 18000,
      comments: 42,
      image: "https://picsum.photos/800/400?random=22"
    },
    {
      id: 23,
      title: "The Best Hiking Trails in the World",
      author: "Mark Johnson",
      summary: "Love hiking? Check out the top hiking trails around the globe for an unforgettable adventure...",
      category: "Travel",
      date: "2024-08-24",
      views: 14500,
      comments: 60,
      image: "https://picsum.photos/800/400?random=23"
    },
    {
      id: 24,
      title: "How to Build a Startup from Scratch",
      author: "Emily White",
      summary: "Starting a business can be daunting. Follow these steps to build your startup from the ground up...",
      category: "Business",
      date: "2024-08-23",
      views: 16000,
      comments: 58,
      image: "https://picsum.photos/800/400?random=24"
    },
    {
      id: 25,
      title: "Tips for a Balanced and Healthy Lifestyle",
      author: "David Brown",
      summary: "Living a healthy lifestyle is all about balance. Learn how to incorporate good habits into your daily routine...",
      category: "Health",
      date: "2024-08-22",
      views: 12500,
      comments: 32,
      image: "https://picsum.photos/800/400?random=25"
    },
    {
      id: 26,
      title: "Top 10 Cities to Visit in 2024",
      author: "Sara Wilson",
      summary: "From bustling metropolises to hidden gems, these cities should be on your travel list for 2024...",
      category: "Travel",
      date: "2024-08-21",
      views: 17000,
      comments: 45,
      image: "https://picsum.photos/800/400?random=26"
    },
    {
      id: 27,
      title: "How to Create a Minimalist Home",
      author: "Lisa Adams",
      summary: "Minimalism is all about simplicity. Here’s how to transform your home into a minimalist haven...",
      category: "Lifestyle",
      date: "2024-08-20",
      views: 9500,
      comments: 20,
      image: "https://picsum.photos/800/400?random=27"
    },
    {
      id: 28,
      title: "The Best Workout Routines for Busy People",
      author: "Peter Collins",
      summary: "Too busy to work out? These quick and effective routines will help you stay fit even with a packed schedule...",
      category: "Health",
      date: "2024-08-19",
      views: 11500,
      comments: 33,
      image: "https://picsum.photos/800/400?random=28"
    },
    {
      id: 29,
      title: "How to Succeed in a Competitive Job Market",
      author: "Chris Green",
      summary: "Landing a job in today’s market can be tough. These strategies will help you stand out from the competition...",
      category: "Business",
      date: "2024-08-18",
      views: 14000,
      comments: 54,
      image: "https://picsum.photos/800/400?random=29"
    },
    {
      id: 30,
      title: "Top 5 Ways to Reduce Your Carbon Footprint",
      author: "Anna Baker",
      summary: "Looking to live a more sustainable lifestyle? Start with these simple tips to reduce your carbon footprint...",
      category: "Environment",
      date: "2024-08-17",
      views: 13000,
      comments: 40,
      image: "https://picsum.photos/800/400?random=30"
    },
    {
      id: 31,
      title: "How to Save Money on Your Next Vacation",
      author: "John Lee",
      summary: "Traveling on a budget? Learn how to save money on flights, hotels, and more with these tips...",
      category: "Travel",
      date: "2024-08-16",
      views: 15000,
      comments: 47,
      image: "https://picsum.photos/800/400?random=31"
    },
    {
      id: 32,
      title: "The Importance of Work-Life Balance",
      author: "Rachel King",
      summary: "Balancing work and personal life can be challenging. Here's how to achieve a healthy work-life balance...",
      category: "Lifestyle",
      date: "2024-08-15",
      views: 12000,
      comments: 25,
      image: "https://picsum.photos/800/400?random=32"
    },
    {
      id: 33,
      title: "The Best Electric Vehicles to Buy in 2024",
      author: "Nathan Harris",
      summary: "Electric vehicles are more popular than ever. Check out the top electric cars to buy in 2024...",
      category: "Automotive",
      date: "2024-08-14",
      views: 18000,
      comments: 55,
      image: "https://picsum.photos/800/400?random=33"
    },
    {
      id: 34,
      title: "How to Invest in the Stock Market",
      author: "Olivia Parker",
      summary: "Investing in stocks can be daunting for beginners. Here’s a guide to getting started with stock market investments...",
      category: "Finance",
      date: "2024-08-13",
      views: 20000,
      comments: 60,
      image: "https://picsum.photos/800/400?random=34"
    },
    {
      id: 35,
      title: "Top 10 Most Scenic Road Trips in the US",
      author: "Ella Thompson",
      summary: "Planning a road trip? Here are the most scenic routes to take across the US for unforgettable views...",
      category: "Travel",
      date: "2024-08-12",
      views: 17000,
      comments: 40,
      image: "https://picsum.photos/800/400?random=35"
    },
    {
      id: 36,
      title: "How to Improve Your Public Speaking Skills",
      author: "Sophia Lee",
      summary: "Public speaking can be intimidating. Follow these tips to improve your confidence and speaking abilities...",
      category: "Lifestyle",
      date: "2024-08-11",
      views: 14500,
      comments: 35,
      image: "https://picsum.photos/800/400?random=36"
    },
    {
      id: 37,
      title: "The Impact of Social Media on Mental Health",
      author: "Ryan Scott",
      summary: "Social media is everywhere, but it can take a toll on mental health. Learn how to manage your social media use...",
      category: "Health",
      date: "2024-08-10",
      views: 16000,
      comments: 50,
      image: "https://picsum.photos/800/400?random=37"
    },
    {
      id: 38,
      title: "The Future of Renewable Energy",
      author: "Grace Moore",
      summary: "Renewable energy is on the rise. Here’s how solar, wind, and other renewable sources are shaping the future...",
      category: "Environment",
      date: "2024-08-09",
      views: 19000,
      comments: 65,
      image: "https://picsum.photos/800/400?random=38"
    },
    {
      id: 39,
      title: "How to Manage Stress Effectively",
      author: "Daniel Brooks",
      summary: "Stress is part of life, but managing it effectively can improve your quality of life. Learn stress management techniques...",
      category: "Health",
      date: "2024-08-08",
      views: 12000,
      comments: 20,
      image: "https://picsum.photos/800/400?random=39"
    },
    {
      id: 40,
      title: "How to Plan a Budget-Friendly Wedding",
      author: "Megan Wright",
      summary: "Weddings can be expensive, but with the right planning, you can have the wedding of your dreams without breaking the bank...",
      category: "Lifestyle",
      date: "2024-08-06",
      views: 11000,
      comments: 30,
      image: "https://picsum.photos/800/400?random=41"
    },
    {
      id: 41,
      title: "The Top 5 Programming Languages to Learn in 2024",
      author: "Liam Carter",
      summary: "Programming is an essential skill in today's world. These are the top languages to learn in 2024...",
      category: "Technology",
      date: "2024-08-05",
      views: 25000,
      comments: 85,
      image: "https://picsum.photos/800/400?random=42"
    },
    {
      id: 42,
      title: "The Best Fitness Apps to Keep You on Track",
      author: "Emma Turner",
      summary: "Stay motivated and achieve your fitness goals with these top fitness apps for 2024...",
      category: "Health",
      date: "2024-08-04",
      views: 14000,
      comments: 45,
      image: "https://picsum.photos/800/400?random=43"
    },
    {
      id: 43,
      title: "How to Decorate Your Home on a Budget",
      author: "Grace Martin",
      summary: "Looking to refresh your home decor without spending a fortune? These tips will help you achieve a stylish look on a budget...",
      category: "Lifestyle",
      date: "2024-08-03",
      views: 13000,
      comments: 35,
      image: "https://picsum.photos/800/400?random=44"
    },
    {
      id: 44,
      title: "Understanding Cryptocurrency in 2024",
      author: "Ethan Davis",
      summary: "Cryptocurrency is evolving rapidly. Here’s what you need to know to navigate the world of digital currency in 2024...",
      category: "Finance",
      date: "2024-08-02",
      views: 23000,
      comments: 90,
      image: "https://picsum.photos/800/400?random=45"
    },
    {
      id: 45,
      title: "How Climate Change is Affecting Global Weather Patterns",
      author: "Isabella Johnson",
      summary: "Climate change is altering weather patterns around the globe. Explore the impacts and the science behind these changes...",
      category: "Environment",
      date: "2024-08-01",
      views: 18000,
      comments: 55,
      image: "https://picsum.photos/800/400?random=46"
    },
    {
      id: 46,
      title: "The Rise of Remote Learning in 2024",
      author: "Jacob Harris",
      summary: "Remote learning is becoming increasingly common. Learn how this educational trend is reshaping the future of education...",
      category: "Education",
      date: "2024-07-31",
      views: 19500,
      comments: 60,
      image: "https://picsum.photos/800/400?random=47"
    },
    {
      id: 47,
      title: "How to Start a Podcast: A Step-by-Step Guide",
      author: "Madison Lewis",
      summary: "Podcasts are a great way to share your voice and ideas. Learn how to start your own podcast with this simple guide...",
      category: "Business",
      date: "2024-07-30",
      views: 14500,
      comments: 25,
      image: "https://picsum.photos/800/400?random=48"
    },
    {
      id: 48,
      title: "How to Cook Healthy Meals in Under 30 Minutes",
      author: "Noah Clark",
      summary: "Short on time but still want to eat healthy? These quick and easy meal ideas are perfect for busy schedules...",
      category: "Health",
      date: "2024-07-29",
      views: 12000,
      comments: 35,
      image: "https://picsum.photos/800/400?random=49"
    },
    {
      id: 49,
      title: "Top 5 Gadgets to Watch Out for in 2024",
      author: "Ava Cooper",
      summary: "Technology is moving fast. Keep an eye on these innovative gadgets expected to make waves in 2024...",
      category: "Technology",
      date: "2024-07-28",
      views: 25000,
      comments: 75,
      image: "https://picsum.photos/800/400?random=50"
    },
    {
      id: 50,
      title: "How to Stay Organized in a Busy World",
      author: "Charlotte Baker",
      summary: "Staying organized is key to reducing stress. Here are some effective ways to stay on top of your tasks...",
      category: "Lifestyle",
      date: "2024-07-27",
      views: 11000,
      comments: 28,
      image: "https://picsum.photos/800/400?random=51"
    }
  ];
export default portalData  